#!/usr/bin/env bash
# Runs automatically at the start of every Claude Code cloud session.
# Reads secrets from environment variables (set in Claude Code web UI)
# and writes agent/.env so the Python agent can authenticate.

set -e
REPO="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO/agent/.env"

echo "=== Session setup starting ==="

# ── 1. GCP service account key ────────────────────────────────────────────────
if [ -n "$GCP_SA_KEY_B64" ]; then
  SA_KEY_FILE="/tmp/gcp-sa-key.json"
  echo "$GCP_SA_KEY_B64" | base64 -d > "$SA_KEY_FILE"
  chmod 600 "$SA_KEY_FILE"
  echo "✓ GCP service account key written to $SA_KEY_FILE"
else
  echo "⚠ GCP_SA_KEY_B64 not set — Firestore will not work"
  SA_KEY_FILE=""
fi

# ── 2. Determine trading mode ─────────────────────────────────────────────────
# TRADING_MODE must be explicitly set to "testnet" or "live".
# If unset, Claude MUST ask the user before any trade can execute.
if [ -z "$TRADING_MODE" ]; then
  RESOLVED_MODE="UNSET"
  echo ""
  echo "╔══════════════════════════════════════════════════════════════╗"
  echo "║  ⚠️  TRADING_MODE IS NOT CONFIGURED                          ║"
  echo "║  Claude must ask you which mode to use before trading.       ║"
  echo "║  Options:  testnet (paper money)  |  live (REAL MONEY)       ║"
  echo "╚══════════════════════════════════════════════════════════════╝"
  echo ""
elif [ "$TRADING_MODE" = "live" ]; then
  RESOLVED_MODE="LIVE"
  echo ""
  echo "╔══════════════════════════════════════════════════════════════╗"
  echo "║  🔴  LIVE TRADING MODE ACTIVE — REAL MONEY AT RISK           ║"
  echo "║  Claude must confirm with you before executing ANY trade.    ║"
  echo "╚══════════════════════════════════════════════════════════════╝"
  echo ""
else
  RESOLVED_MODE="TESTNET"
  echo ""
  echo "╔══════════════════════════════════════════════════════════════╗"
  echo "║  🟡  TESTNET MODE — paper money only, no real funds at risk  ║"
  echo "╚══════════════════════════════════════════════════════════════╝"
  echo ""
fi

# ── 3. Write agent/.env ───────────────────────────────────────────────────────
{
  echo "# Auto-generated by .claude/setup-session.sh — do not commit"
  [ -n "$SA_KEY_FILE" ] && echo "GOOGLE_APPLICATION_CREDENTIALS=$SA_KEY_FILE"
  [ -n "$BINANCE_API_KEY" ]    && echo "BINANCE_API_KEY=$BINANCE_API_KEY"
  [ -n "$BINANCE_API_SECRET" ] && echo "BINANCE_API_SECRET=$BINANCE_API_SECRET"
  # Only write TRADING_MODE if it was explicitly set — leave it absent if UNSET
  # so executor.py also detects the unconfigured state
  [ "$RESOLVED_MODE" != "UNSET" ] && echo "TRADING_MODE=${TRADING_MODE}"
} > "$ENV_FILE"
echo "✓ agent/.env written (TRADING_MODE=$RESOLVED_MODE)"

# ── 4. Install Python agent dependencies ─────────────────────────────────────
if [ -f "$REPO/agent/requirements.txt" ]; then
  pip install -q -r "$REPO/agent/requirements.txt" 2>&1 | tail -3
  echo "✓ agent/requirements.txt installed"
fi

# ── 5. Quick Firestore connectivity smoke test ───────────────────────────────
if [ -n "$SA_KEY_FILE" ]; then
  python3 - <<'PYEOF'
import os, sys
os.environ.setdefault("GOOGLE_APPLICATION_CREDENTIALS", "/tmp/gcp-sa-key.json")
try:
    from google.cloud import firestore
    db = firestore.Client(project="tradingbot-496815")
    db.collection("_ping").document("_ping")
    print("✓ Firestore client initialised (project=tradingbot-496815)")
except Exception as e:
    print(f"✗ Firestore init failed: {e}", file=sys.stderr)
PYEOF
fi

echo ""
echo "=== Session setup complete ==="
echo "TRADING_MODE : $RESOLVED_MODE"
echo "GCP CREDS    : $([ -n "$SA_KEY_FILE" ] && echo 'present' || echo 'MISSING')"
echo "BINANCE KEYS : $([ -n "$BINANCE_API_KEY" ] && echo 'present' || echo 'MISSING')"
echo ""
