#!/usr/bin/env bash
# Runs automatically at the start of every Claude Code cloud session.

set -e
REPO="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO/agent/.env"
SA_KEY_REPO="$REPO/sa-key.json"
SA_KEY_FILE="/tmp/gcp-sa-key.json"

TELEGRAM_TOKEN="8637585030:AAGNJ8Zj0JemJxKz5MzBYTteWTknsc5lCfA"
TELEGRAM_CHAT_ID="8293278264"
CLOUD_RUN_URL="https://tradingbot-grpyjoqoaq-ew.a.run.app"

echo "=== Session setup starting ==="

# ── 1. GCP service account key ────────────────────────────────────────────────
if [ -n "$GCP_SA_KEY_B64" ]; then
  echo "$GCP_SA_KEY_B64" | base64 -d > "$SA_KEY_FILE"
  chmod 600 "$SA_KEY_FILE"
  echo "✓ GCP SA key from env var"
elif [ -f "$SA_KEY_REPO" ]; then
  cp "$SA_KEY_REPO" "$SA_KEY_FILE"
  chmod 600 "$SA_KEY_FILE"
  echo "✓ GCP SA key from repo file"
else
  echo "⚠ No SA key found — Firestore will not work"
  SA_KEY_FILE=""
fi
export GOOGLE_APPLICATION_CREDENTIALS="$SA_KEY_FILE"

# ── 2. Trading mode banner ────────────────────────────────────────────────────
TRADING_MODE="${TRADING_MODE:-testnet}"
export TRADING_MODE

if [ "$TRADING_MODE" = "live" ]; then
  RESOLVED_MODE="LIVE"
  echo ""
  echo "╔══════════════════════════════════════════════════════════════╗"
  echo "║  🔴  LIVE TRADING MODE — REAL MONEY AT RISK                  ║"
  echo "╚══════════════════════════════════════════════════════════════╝"
  echo ""
else
  RESOLVED_MODE="TESTNET"
  echo ""
  echo "╔══════════════════════════════════════════════════════════════╗"
  echo "║  🟡  TESTNET MODE — paper money, no real funds at risk       ║"
  echo "╚══════════════════════════════════════════════════════════════╝"
  echo ""
fi

# ── 3. Write agent/.env ───────────────────────────────────────────────────────
{
  echo "# Auto-generated by .claude/setup-session.sh"
  echo "GOOGLE_APPLICATION_CREDENTIALS=$SA_KEY_FILE"
  echo "TRADING_MODE=$TRADING_MODE"
  echo "BYBIT_API_KEY=${BYBIT_API_KEY:-x28DIhmPtaPyoNhGG1}"
  echo "BYBIT_API_SECRET=${BYBIT_API_SECRET:-0HLHaLi5Axnlsvr3eAae8S7LWb4UAKGL9h3z}"
  echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_TOKEN"
  echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID"
  echo "CLOUD_RUN_URL=$CLOUD_RUN_URL"
} > "$ENV_FILE"
echo "✓ agent/.env written"

# ── 4. Install dependencies ───────────────────────────────────────────────────
pip install -q -r "$REPO/agent/requirements.txt" 2>&1 | tail -1
echo "✓ dependencies ready"

# ── 5. Notify Telegram that session is live ───────────────────────────────────
BOT_STATUS=$(curl -sf "$CLOUD_RUN_URL/health" 2>/dev/null || echo '{"status":"unreachable"}')
POSITIONS=$(python3 -c "
import os, sys
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '$SA_KEY_FILE'
sys.path.insert(0, '$REPO')
try:
    from agent.state import get_all_positions
    p = get_all_positions()
    print(f'{len(p)} open' if p else 'none')
except Exception as e:
    print('unknown')
" 2>/dev/null)

MSG="🤖 <b>Claude trading session started</b>
Mode: $RESOLVED_MODE
Positions: $POSITIONS
Bot: $BOT_STATUS
Ready for analysis and execution."

curl -sf -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
  -H "Content-Type: application/json" \
  -d "{\"chat_id\":\"$TELEGRAM_CHAT_ID\",\"text\":\"$MSG\",\"parse_mode\":\"HTML\"}" \
  > /dev/null 2>&1 && echo "✓ Telegram notified" || echo "⚠ Telegram notification failed (network restricted)"

echo ""
echo "=== Session setup complete ==="
echo "TRADING_MODE : $RESOLVED_MODE"
echo "GCP CREDS    : $([ -n "$SA_KEY_FILE" ] && echo 'present' || echo 'MISSING')"
echo "BYBIT KEYS   : present (testnet)"
echo ""
