#!/usr/bin/env bash
# Runs automatically at the start of every Claude Code cloud session.
# Reads secrets from environment variables (set in Claude Code web UI)
# and writes agent/.env so the Python agent can authenticate.

set -e
REPO="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO/agent/.env"

echo "=== Session setup starting ==="

# ── 1. GCP service account key ────────────────────────────────────────────────
if [ -n "$GCP_SA_KEY_B64" ]; then
  SA_KEY_FILE="/tmp/gcp-sa-key.json"
  echo "$GCP_SA_KEY_B64" | base64 -d > "$SA_KEY_FILE"
  chmod 600 "$SA_KEY_FILE"
  echo "✓ GCP service account key written to $SA_KEY_FILE"
else
  echo "⚠ GCP_SA_KEY_B64 not set — Firestore will not work"
  SA_KEY_FILE=""
fi

# ── 2. Write agent/.env ───────────────────────────────────────────────────────
{
  echo "# Auto-generated by .claude/setup-session.sh — do not commit"
  [ -n "$SA_KEY_FILE" ] && echo "GOOGLE_APPLICATION_CREDENTIALS=$SA_KEY_FILE"
  [ -n "$BINANCE_API_KEY" ]    && echo "BINANCE_API_KEY=$BINANCE_API_KEY"
  [ -n "$BINANCE_API_SECRET" ] && echo "BINANCE_API_SECRET=$BINANCE_API_SECRET"
  echo "TRADING_MODE=${TRADING_MODE:-testnet}"
} > "$ENV_FILE"
echo "✓ agent/.env written"

# ── 3. Install Python agent dependencies ─────────────────────────────────────
if [ -f "$REPO/agent/requirements.txt" ]; then
  pip install -q -r "$REPO/agent/requirements.txt" 2>&1 | tail -3
  echo "✓ agent/requirements.txt installed"
fi

# ── 4. Quick connectivity smoke test ─────────────────────────────────────────
if [ -n "$SA_KEY_FILE" ]; then
  python3 - <<'PYEOF'
import os, sys
os.environ.setdefault("GOOGLE_APPLICATION_CREDENTIALS", "/tmp/gcp-sa-key.json")
try:
    from google.cloud import firestore
    db = firestore.Client(project="tradingbot-496815")
    db.collection("_ping").document("_ping")  # just constructs a ref, no network call
    print("✓ Firestore client initialised (project=tradingbot-496815)")
except Exception as e:
    print(f"✗ Firestore init failed: {e}", file=sys.stderr)
PYEOF
fi

echo "=== Session setup complete — ready to trade ==="
